In [1]:
import os
import pandas as pd

base_dir = '../results/'

In [22]:
target = base_dir + 'result_0318_214812.csv'

In [23]:
df = pd.read_csv(target)
df

,seed,coins,maxTime,noteTime,numMachines,maxPayout,meanPayout,minPayout,score
0,1001,5797,8017,2,5,1.629630,1.138330,0.634111,7185.0
1,1002,8662,6961,9,9,1.555222,0.800432,0.379414,11775.0
2,1003,4407,6097,7,8,2.291667,1.150530,0.212859,9013.0
3,1004,2931,9073,2,8,2.626953,0.899991,0.211683,16542.0
4,1005,8577,8209,9,6,2.481778,1.285108,0.344238,15178.0
5,1006,1541,7153,9,3,0.870802,0.698345,0.486516,0.0
6,1007,7187,9937,5,9,2.870023,0.950786,0.474074,20884.0
7,1008,3272,4082,7,4,1.781665,0.825241,0.275556,5146.0
8,1009,8917,6866,5,3,0.901693,0.498527,0.254630,7228.0
9,1010,1882,5810,3,8,2.200000,1.119705,0.350000,6184.0
10,1011,7527,4946,9,6,1.167407,0.816390,0.380000,6745.0
11,1012,6052,4274,4,6,2.129630,1.173108,0.744598,9928.0
12,1013,1797,7058,2,4,1.319512,1.109581,0.586880,3425.0
13,1014,4662,6002,2,9,4.526239,1.210092,0.471111,19354.0
14,1015,407,5138,7,8,1.183680,0.856213,0.379009,0.0
15,1016,8832,4465,4,8,2.675000,1.283253,0.585000,17580.0
16,1017,4577,7249,8,6,2.699259,1.020210,0.418381,14023.0
17,1018,7442,6193,9,3,0.920320,0.674413,0.394440,5969.0
18,1019,3187,5329,6,9,1.921455,0.923171,0.383301,3973.0
19,1020,1712,8305,10,9,1.181885,0.840120,0.400000,3675.0
20,1021,7357,7441,8,8,1.504320,0.979114,0.644719,11709.0
21,1022,321,6385,6,4,2.148760,1.370234,0.420000,5806.0
22,1023,5967,5521,4,3,1.882760,1.164386,0.503822,10019.0
23,1024,6076,2591,8,10,3.300000,1.203936,0.598543,10905.0
24,1025,1820,1727,4,8,1.611022,1.024309,0.660218,1263.0
25,1026,4686,671,4,5,2.030178,1.410566,0.822029,5240.0
26,1027,430,3455,2,4,1.526108,1.137142,0.722409,2154.0
27,1028,8856,2783,6,4,1.279259,1.005304,0.882053,10483.0
28,1029,4600,1919,4,10,1.746807,1.092046,0.568889,6441.0
29,1030,7466,863,2,7,1.709630,0.975342,0.564642,7232.0
...,...,...,...,...,...,...,...,...,...
970,1971,1507,7759,5,6,2.204861,0.918774,0.376157,8493.0
971,1972,9933,834,2,6,1.821470,0.974507,0.142750,9967.0
972,1973,5678,9871,6,5,1.150010,0.778837,0.270473,6832.0
973,1974,8543,8815,6,10,2.032363,0.858141,0.330579,12593.0
974,1975,4288,7951,4,8,1.018032,0.682128,0.318616,4583.0
975,1976,2812,1026,8,8,1.868480,1.068871,0.518303,2754.0
976,1977,8458,162,6,6,1.573433,0.897022,0.300526,8747.0
977,1978,1422,9007,4,3,0.767352,0.712196,0.678175,0.0
978,1979,7068,8143,10,10,2.374155,0.867151,0.278519,16350.0
979,1980,5592,1218,6,10,1.607510,0.907269,0.443823,5219.0
980,1981,1337,354,3,8,2.445335,1.065260,0.558400,2100.0
981,1982,4202,9199,3,5,1.382778,0.822578,0.589253,6183.0
982,1983,9848,2082,8,3,1.378601,0.786910,0.417260,10603.0
983,1984,911,2945,7,8,1.119068,0.852577,0.544218,1186.0
984,1985,6557,5729,4,7,1.668837,0.974854,0.322030,11003.0
985,1986,9422,4673,2,4,1.848579,0.747058,0.358796,10798.0
986,1987,5167,3809,9,10,1.777346,1.038153,0.580000,6898.0
987,1988,3691,6785,4,10,1.649136,1.090323,0.493855,4336.0
988,1989,9337,5921,2,8,1.510279,0.865084,0.519382,9783.0
989,1990,2301,4865,2,5,1.385185,0.725714,0.347222,4366.0
990,1991,7947,4001,9,4,2.637037,1.219191,0.154756,13220.0
991,1992,6472,6977,4,4,1.289554,0.999101,0.622428,8669.0
992,1993,2216,6113,10,10,4.297521,1.450859,0.801749,20208.0
993,1994,5082,5057,8,7,1.327796,0.950630,0.583496,4882.0
994,1995,826,4193,6,5,0.766667,0.463831,0.236664,0.0
995,1996,9252,7169,10,5,2.080000,1.368669,0.335648,13793.0
996,1997,4996,6305,8,4,1.087360,0.720541,0.466472,4763.0
997,1998,7862,5249,6,8,3.720850,1.319429,0.472960,16663.0
998,1999,3606,4385,3,7,1.126543,0.869561,0.510204,3660.0
999,2000,9592,2177,6,10,5.034722,1.281788,0.385742,17655.0

In [24]:
df[df.coins > df.score].describe()

,seed,coins,maxTime,noteTime,numMachines,maxPayout,meanPayout,minPayout,score
count,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000
mean,1536.384000,4931.460000,4057.548000,6.272000,6.188000,1.327348,0.841950,0.475030,4286.212000
std,277.956435,3001.728918,2981.659543,2.517014,2.278028,0.524567,0.185324,0.174445,2979.022495
min,1006.000000,117.000000,118.000000,2.000000,3.000000,0.532494,0.393333,0.000000,0.000000
25%,1306.000000,2224.500000,1387.500000,4.000000,4.000000,0.987759,0.727901,0.361117,1680.000000
50%,1575.000000,5010.000000,3428.500000,6.000000,6.000000,1.201457,0.829296,0.480841,4523.500000
75%,1770.750000,7552.000000,6653.250000,8.000000,8.000000,1.516097,0.948958,0.582886,6972.500000
max,1997.000000,9961.000000,9982.000000,10.000000,10.000000,4.080000,1.693426,1.040968,9765.000000

In [25]:
df[df.score == 0].describe()

,seed,coins,maxTime,noteTime,numMachines,maxPayout,meanPayout,minPayout,score
count,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.000000,29.0
mean,1596.517241,677.034483,5534.344828,6.379310,6.034483,1.726462,0.952441,0.509226,0.0
std,307.513022,677.403155,3016.931533,2.455516,2.367681,0.932959,0.278658,0.194514,0.0
min,1006.000000,117.000000,627.000000,2.000000,3.000000,0.766667,0.463831,0.185185,0.0
25%,1360.000000,228.000000,2938.000000,4.000000,4.000000,1.112960,0.734567,0.390000,0.0
50%,1653.000000,373.000000,5227.000000,6.000000,5.000000,1.413454,0.903965,0.486516,0.0
75%,1816.000000,1111.000000,8579.000000,9.000000,8.000000,1.914815,1.101201,0.608565,0.0
max,1995.000000,2897.000000,9701.000000,10.000000,10.000000,4.080000,1.693426,1.040968,0.0

In [26]:
df[(df.score > df.coins * 1.2)].describe()

,seed,coins,maxTime,noteTime,numMachines,maxPayout,meanPayout,minPayout,score
count,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000,550.000000
mean,1490.172727,4671.970909,6045.149091,5.850909,6.743636,2.032903,1.055225,0.494071,9579.478182
std,293.844669,2764.418789,2423.154814,2.594577,2.244139,0.831952,0.212125,0.188947,5607.984169
min,1001.000000,115.000000,354.000000,2.000000,3.000000,0.843003,0.575489,0.040000,581.000000
25%,1226.000000,2223.500000,4115.500000,4.000000,5.000000,1.499444,0.906570,0.365303,5443.750000
50%,1495.000000,4431.000000,6190.000000,6.000000,7.000000,1.799244,1.032121,0.482381,8850.000000
75%,1749.750000,6918.500000,8035.500000,8.000000,9.000000,2.308812,1.165591,0.598180,12424.750000
max,2000.000000,9991.000000,9996.000000,10.000000,10.000000,6.743050,1.991800,1.296667,38100.000000

In [27]:
df[(df.score < df.coins * 0.8)].describe()

,seed,coins,maxTime,noteTime,numMachines,maxPayout,meanPayout,minPayout,score
count,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000,86.000000
mean,1525.127907,2665.895349,5580.604651,6.267442,6.011628,1.353514,0.817694,0.457636,1594.941860
std,292.777603,2569.367727,2776.647718,2.586956,2.373849,0.693077,0.226851,0.189573,1935.660935
min,1006.000000,117.000000,627.000000,2.000000,3.000000,0.532494,0.393333,0.000000,0.000000
25%,1279.500000,607.500000,3155.750000,4.000000,4.000000,0.904223,0.686619,0.326247,0.000000
50%,1583.000000,1705.000000,5529.500000,6.000000,6.000000,1.136460,0.780777,0.448249,815.500000
75%,1757.500000,4160.500000,8070.750000,9.000000,8.000000,1.597020,0.917097,0.584683,2653.500000
max,1995.000000,9365.000000,9982.000000,10.000000,10.000000,4.080000,1.693426,1.040968,7051.000000

In [28]:
df[df.score == 0]

,seed,coins,maxTime,noteTime,numMachines,maxPayout,meanPayout,minPayout,score
5,1006,1541,7153,9,3,0.870802,0.698345,0.486516,0.0
14,1015,407,5138,7,8,1.183680,0.856213,0.379009,0.0
36,1037,260,2303,7,5,1.007451,0.770769,0.542500,0.0
164,1165,402,8667,6,9,4.009770,1.187551,0.475583,0.0
226,1227,1111,3373,9,5,1.365498,0.686262,0.185185,0.0
317,1318,290,5227,9,3,1.207321,1.101201,1.040968,0.0
331,1332,460,2731,3,9,1.521920,0.903965,0.410000,0.0
359,1360,119,7722,7,5,4.080000,1.693426,0.564869,0.0
448,1449,347,2938,6,4,1.308457,0.696381,0.327988,0.0
471,1472,1482,4954,6,7,2.847222,1.215378,0.719752,0.0
498,1499,177,1786,3,5,2.587340,1.475713,0.608565,0.0
605,1606,1874,9221,9,10,1.814425,0.918170,0.601957,0.0
624,1625,569,9701,6,9,1.112960,0.686786,0.296769,0.0
649,1650,313,3544,4,7,1.914815,1.011802,0.540000,0.0
652,1653,228,1144,10,4,1.280639,0.992603,0.775328,0.0
659,1660,143,2392,9,9,1.829768,0.982372,0.415452,0.0
680,1681,173,5316,2,7,1.607814,0.897669,0.325667,0.0
714,1715,1222,8579,10,7,1.016320,0.734567,0.541250,0.0
771,1772,1505,9524,8,3,1.042274,0.810129,0.678113,0.0
780,1781,371,7508,8,8,2.013027,0.867698,0.420000,0.0
794,1795,145,627,5,4,1.850000,1.158591,0.711474,0.0
815,1816,230,3027,8,7,3.720980,1.491648,0.764444,0.0
915,1916,428,1572,6,8,2.460000,1.169484,0.187829,0.0
929,1930,202,8239,3,5,1.413454,1.054651,0.415452,0.0
932,1933,117,9487,2,10,1.564640,0.913876,0.390000,0.0
943,1944,373,5744,4,3,1.132813,0.834754,0.597668,0.0
968,1969,2897,9679,9,3,0.770000,0.634762,0.450370,0.0
977,1978,1422,9007,4,3,0.767352,0.712196,0.678175,0.0
994,1995,826,4193,6,5,0.766667,0.463831,0.236664,0.0

In [29]:
df[df.coins < 300]

,seed,coins,maxTime,noteTime,numMachines,maxPayout,meanPayout,minPayout,score
36,1037,260,2303,7,5,1.007451,0.770769,0.542500,0.0
75,1076,175,3551,7,10,1.643519,1.039242,0.641784,1279.0
189,1190,147,2510,4,7,1.570370,0.944720,0.477264,2011.0
214,1215,232,1262,4,3,0.740741,0.645300,0.483398,245.0
317,1318,290,5227,9,3,1.207321,1.101201,1.040968,0.0
320,1321,204,6474,8,8,1.548952,0.772432,0.309606,3420.0
359,1360,119,7722,7,5,4.080000,1.693426,0.564869,0.0
487,1488,262,538,6,9,1.505237,0.950601,0.409650,266.0
498,1499,177,1786,3,5,2.587340,1.475713,0.608565,0.0
652,1653,228,1144,10,4,1.280639,0.992603,0.775328,0.0
659,1660,143,2392,9,9,1.829768,0.982372,0.415452,0.0
680,1681,173,5316,2,7,1.607814,0.897669,0.325667,0.0
766,1767,200,103,7,9,1.015040,0.678966,0.275879,202.0
773,1774,115,1351,6,6,1.471193,0.888235,0.436959,1219.0
787,1788,285,8756,8,4,1.523438,1.113594,0.312500,581.0
794,1795,145,627,5,4,1.850000,1.158591,0.711474,0.0
815,1816,230,3027,8,7,3.720980,1.491648,0.764444,0.0
901,1902,258,4068,2,10,3.576389,1.057569,0.366211,10330.0
922,1923,288,6991,4,8,1.550987,0.929992,0.578802,3815.0
929,1930,202,8239,3,5,1.413454,1.054651,0.415452,0.0
932,1933,117,9487,2,10,1.564640,0.913876,0.390000,0.0